### ISSUE TITLE
bug: occasional build crush

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#19]
Build occasionally crushes on`npm test` due to the test exception which is not fulfilled:

```
  1 failing

  1) Contract: PrimeToken
       vesting: edgecases - timestamp < _cliff
         » timestamp < _cliff
           reverts:
     AssertionError: Expected an exception but none was received
      at expectException (node_modules/@openzeppelin/test-helpers/src/expectRevert.js:25:10)
      at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by kinspotting** [comment]
Solved in https://github.com/PrimeDAO/contracts/pull/17
