### ISSUE TITLE
Bug: BigInt error on coverage check

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#22]
Trying to run `npm run coverage` and on  `Contract: StakingRewards / # exit / ` bumping into the following error:

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at _stringify (/home/tengree/Projects/primedao/contracts/node_modules/mocha/lib/utils.js:270:20)
    at jsonStringify (/home/tengree/Projects/primedao/contracts/node_modules/mocha/lib/utils.js:221:12)
    at Object.exports.stringify (/home/tengree/Projects/primedao/contracts/node_modules/mocha/lib/utils.js:193:14)
    at stringifyDiffObjs (/home/tengree/Projects/primedao/contracts/node_modules/mocha/lib/reporters/base.js:181:24)
    at Runner.<anonymous> (/home/tengree/Projects/primedao/contracts/node_modules/mocha/lib/reporters/base.js:332:7)
    at Runner.emit (events.js:187:15)

```

**Comment by kinspotting** [comment]
fixed
